### ISSUE TITLE
Enhance User Experience by Updating Navigation Bar

### ISSUE THREAD

**Issue by Sa2003hil** [Open-Source-Chandigarh/Streamix-IMDb#1]
Enhance the user experience of our Streamix updating navigation bar.
Add important links in the navbar like "Home", "About us,"Sign In" etc

**Comment by Larkuo** [comment]
Hello, I'd like to work on this. Can it be assigned to me?

**Comment by Sa2003hil** [comment]
Hey @Larkuo 
Congratulations on opening your first issue in the **Streamix IMDb** repository! 🎉 Your contribution is valuable to us! 😊
Please make sure to follow our Contributing Guidelines. 💪🏻

Our review team will carefully assess the issue and reach out to you soon!
We appreciate your patience!

- The website's navbar includes essential components like a logo, search bar, and sign-in options, ensuring seamless user navigation and account management.
**Sample:-**
![image](https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/115913715/070416a8-78d5-4100-a8fe-f9b304c5c673)

**Comment by Larkuo** [comment]
Hi @Sa2003hil ,
Thank you but it seems like someone else has worked on this issue and a pr has been merged.
Is there something you'd like me to do differently? Or should I work on another issue?

**Comment by Sa2003hil** [comment]
@Larkuo 
In the previous pull request, we only added a hover effect. You can work on transforming the navbar to match the design provided in the description.Good luck with your contribution!

**Comment by Larkuo** [comment]
@Sa2003hil 
Sure thing. I'll do that. Thanks.

**Comment by Sa2003hil** [comment]
Please make sure that you **_star ⭐️ the repo_** ! To add **Hacktobest** label to the issue :)

**Comment by Sa2003hil** [comment]
@Larkuo are you working on this issue ?

**Comment by Larkuo** [comment]
Yes I am. I'll create a pr by tomorrow

**Comment by Sa2003hil** [comment]
@Larkuo ok ! no problem 👍🏻 Take your time .

**Comment by Larkuo** [comment]
@Sa2003hil Sure thing. Thanks.

**Comment by Sa2003hil** [comment]
Hey @Larkuo have you done the issue ?

**Comment by Larkuo** [comment]
Hello @Sa2003hil I have worked on it but haven't made it responsive yet. Should I still create a pull request? This is what I have at the moment. 
![image](https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/46784442/75f4d909-0f43-47d4-9395-6695652a3f4b)

**Comment by Sa2003hil** [comment]
@Larkuo  OK ! how much time do you need ?

**Comment by Larkuo** [comment]
Hello @Sa2003hil ,
My apologies for the delays. I have created a pull request now.

https://github.com/Open-Source-Chandigarh/Streamix-IMDb/pull/22
