### ISSUE TITLE
Add placeholder message in "Contact us" input

### ISSUE THREAD

**Issue by PrajwalGraj** [Open-Source-Chandigarh/Streamix-IMDb#12]
**Describe the Issue**
To add Placeholder message in the “Contact From” which will help in improving the User experience.

**To Reproduce**
1. Go to Website
2. Click on ‘Contact’ or scroll down 
3. Make changes and help in adding placeholder message there

**Screenshots**
<img width="1421" alt="Screenshot 2023-10-23 at 11 30 14 AM" src="https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/113518358/eecc28d5-f4dc-46df-8c3a-e032f2e76f8d">

**Comment by PrajwalGraj** [comment]
@Sa2003hil If you are fine with this issue please add required labels so that it will help contributors

**Comment by Sa2003hil** [comment]
@PrajwalGraj You can create more **'Good First Issues' in Streamix**; it is beneficial for fellow contributors.

**Comment by PrajwalGraj** [comment]
@Sa2003hil Ya sure

**Comment by Pooja11kumari** [comment]
I would like to work on it.Can you assign this issue to me @Sa2003hil

**Comment by Sa2003hil** [comment]
Hey @Pooja11kumari 
**Congratulations we are assigning this issue to you ! 🎉** Your forthcoming contribution holds great value for us 😊
Please submit a pull request with a clear explanation of the changes you've made. Kindly ensure that you adhere to our [Contributing Guidelines](https://github.com/Open-Source-Chandigarh/Streamix-IMDb#rules-for-contributions) 💪🏻 and consider giving a star ⭐️ to our repository.

Our review team will carefully assess your merge and reach out to you soon!
We appreciate your patience!

**Comment by Sa2003hil** [comment]
@Pooja11kumari _Consider giving a **star ⭐️ to our repository** for addition of **hactoberfest-accepted** label_
