### ISSUE TITLE
Add Footer Section for Improved User Experience

### ISSUE THREAD

**Issue by Sa2003hil** [Open-Source-Chandigarh/Streamix-IMDb#2]
Make a clean footer for the application.
Footer should include Social Links of Open Source Chandigarh, etc

**Comment by BhukyaShivaNayak** [comment]
Please assign this issue

**Comment by Sa2003hil** [comment]
Hey @BhukyaShivaNayak 
Congratulations we are assigning this issue to you ! 🎉 Your forthcoming contribution holds great value for us 😊
Please submit a pull request with a clear explanation of the changes you've made. Kindly ensure that you adhere to our Contributing Guidelines 💪🏻 and consider giving a star ⭐️ to our repository.

Our review team will carefully assess your merge and reach out to you soon!
We appreciate your patience!
