### ISSUE TITLE
[BUG]Add links to the Logo's in Footer

### ISSUE THREAD

**Issue by PrajwalGraj** [Open-Source-Chandigarh/Streamix-IMDb#26]
**Describe the Issue**
1.Social logos in Footer are just Icons.Add Anchor tag to the logos with respective links.
2.Remove the Image in the footer “An AMAZON Company”

***Screenshot***
<img width="1439" alt="Screenshot 2023-10-27 at 10 06 38 AM" src="https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/113518358/3a80d14f-bff4-4043-a134-e9210265714e">

**Comment by PrajwalGraj** [comment]
@Sa2003hil Shall we add the GitHub repo link in the Social logos?

**Comment by Pooja11kumari** [comment]
I would like to work on it, can you assign  this to me? @Sa2003hil

**Comment by Sa2003hil** [comment]
Hey @Pooja11kumari 
**Congratulations we are assigning this issue to you ! 🎉** Your forthcoming contribution holds great value for us 😊
Please submit a pull request with a clear explanation of the changes you've made. Kindly ensure that you adhere to our [Contributing Guidelines](https://github.com/Open-Source-Chandigarh/Streamix-IMDb#rules-for-contributions) 💪🏻 and consider giving a star ⭐️ to our repository.

Our review team will carefully assess your merge and reach out to you soon!
We appreciate your patience!

**Comment by PrajwalGraj** [comment]
> ?

@Sa2003hil what about this?

**Comment by PrajwalGraj** [comment]
> @Sa2003hil Shall we add the GitHub repo link in the Social logos?

@Sa2003hil what about this? Repo links ya do you something else?

**Comment by Sa2003hil** [comment]
@PrajwalGraj  yes we can ! because it's a open source project so anyone can access the source code through our website

**Comment by PrajwalGraj** [comment]
@Pooja11kumari Add the link of this repo in the Anchor Tag.

**Comment by Pooja11kumari** [comment]
@PrajwalGraj ok
