### ISSUE TITLE
Remove Underline in the LOGO

### ISSUE THREAD

**Issue by PrajwalGraj** [Open-Source-Chandigarh/Streamix-IMDb#28]
**Describe the Issue**
Remove the Blue underline which is present in the NAV Logo.

**Screenshot**
<img width="543" alt="Screenshot 2023-10-27 at 10 35 07 AM" src="https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/113518358/29cb9288-e64c-404b-a4c4-81c109704b0a">

**Comment by Rakshithx7** [comment]
Hey **PrajwalGraj**, I would like to work on this **issue**, Kindly assign this to me.

**Comment by PrajwalGraj** [comment]
@Rakshith-0-7 Iam not the maintainer of this repo.Ask @Sa2003hil about it.

**Comment by Rakshithx7** [comment]
@Sa2003hil I would like to work on this issue, Kindly assign this to me.

**Comment by Sa2003hil** [comment]
Hey @Rakshith-0-7 
**Congratulations we are assigning this issue to you ! 🎉** Your forthcoming contribution holds great value for us 😊
Please submit a pull request with a clear explanation of the changes you've made. Kindly ensure that you adhere to our [Contributing Guidelines](https://github.com/Open-Source-Chandigarh/Streamix-IMDb#rules-for-contributions) 💪🏻 and consider giving a star ⭐️ to our repository.

Our review team will carefully assess your merge and reach out to you soon!
We appreciate your patience!

**Comment by Rakshith-0-7** [comment]
@Sa2003hil Please add "hacktoberfest-accepted" Label
