### ISSUE TITLE
[BUG]Add Anchor Tag to the Button

### ISSUE THREAD

**Issue by PrajwalGraj** [Open-Source-Chandigarh/Streamix-IMDb#33]
***Description of the Issue***
The "Sign in for more access" button has no link.So add a Anchor tag to it.For the link add this Repos link in the Anchor.

***Screenshot***
<img width="488" alt="Screenshot 2023-10-29 at 11 34 40 PM" src="https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/113518358/e4b3a966-b9d6-4a82-8093-ce350961cea6">

**Comment by Pooja11kumari** [comment]
@Sa2003hil I would like to work on it,Can you assign this issue to me
