### ISSUE TITLE
Contact Us Information 

### ISSUE THREAD

**Issue by BowlPulp** [Open-Source-Chandigarh/Streamix-IMDb#36]
The current "Contact Us" menu doesn't store the messages and information provided by the user. Since it is vital to store information about Contact, I'd love to fix this problem.
![image](https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/67683793/5e5ec7bd-9505-4c3c-a548-4a3be413f7b7)
Solution: Information can be directly stored in google sheets/excel.
Kindly assign me this work.

**Comment by Sa2003hil** [comment]
Hey @BowlPulp 
Congratulations we are assigning this issue to you ! 🎉 Your forthcoming contribution holds great value for us 😊
Please submit a pull request with a clear explanation of the changes you've made. Kindly ensure that you adhere to our [Contributing Guidelines](https://github.com/Open-Source-Chandigarh/Streamix-IMDb#rules-for-contributions) 💪🏻 and consider giving a star ⭐️ to our repository.

Our review team will carefully assess your merge and reach out to you soon!
We appreciate your patience!

**Comment by BowlPulp** [comment]
Done! Added DB to store the data - https://github.com/Open-Source-Chandigarh/Streamix-IMDb/pull/37
