### ISSUE TITLE
adding code of conduct

### ISSUE THREAD

**Issue by pinak22dhir** [Open-Source-Chandigarh/Streamix-IMDb#4]
you can add code of conduct

**Comment by pinak22dhir** [comment]
@can you assign this issue to me?

**Comment by pinak22dhir** [comment]
@Sa2003hil  can you assign this issue to me?

**Comment by Sa2003hil** [comment]
**Hey @pinak22dhir !**
Congratulations we are assigning this issue to you ! 🎉 Your forthcoming contribution holds great value for us 😊
Please submit a pull request with a clear explanation of the changes you've made. Kindly ensure that you adhere to our Contributing Guidelines 💪🏻 and consider giving a star ⭐️ to our repository.

Our review team will carefully assess your merge and reach out to you soon!
We appreciate your patience!

**Comment by pinak22dhir** [comment]
@Sa2003hil  added file, have a look.
