### ISSUE TITLE
Develop a carousel slider featuring the latest movies.

### ISSUE THREAD

**Issue by Sa2003hil** [Open-Source-Chandigarh/Streamix-IMDb#7]
Create a feature-rich carousel slider for showcasing the latest movies. Include image transitions, navigation controls, and movie details on hover. 
Sample :
![image](https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/115913715/82f24ca8-6679-4009-be7d-788cc260983a)

**Comment by Wafmulla** [comment]
Can you assign this issue to me under Hacktober fest label?

**Comment by Sa2003hil** [comment]
Hey @Wafmulla 
**Congratulations we are assigning this issue to you ! 🎉** Your forthcoming contribution holds great value for us 😊
Please submit a pull request with a clear explanation of the changes you've made. Kindly ensure that you adhere to our [Contributing Guidelines](https://github.com/Open-Source-Chandigarh/Streamix-IMDb#rules-for-contributions) 💪🏻 and consider giving a star ⭐️ to our repository.

Our review team will carefully assess your merge and reach out to you soon!
We appreciate your patience!
