### ISSUE TITLE
Create Top 5 on IMDb this week (Cards)

### ISSUE THREAD

**Issue by Sa2003hil** [Open-Source-Chandigarh/Streamix-IMDb#8]
Design an attractive and informative set of cards to display the top 5 movies on IMDb for the current week. Each card should include movie posters, titles, ratings, Watch button and brief description.
Sample :
![image](https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/115913715/4075adb2-89ef-4e87-bd0a-0919f24402d0)

**Comment by kshitizvardhan** [comment]
@Sa2003hil  Please Assign me this Issue

**Comment by Sa2003hil** [comment]
Hey @kshitizvardhan 
**Congratulations we are assigning this issue to you !** 🎉 Your forthcoming contribution holds great value for us 😊
Please submit a pull request with a clear explanation of the changes you've made. Kindly ensure that you adhere to our Contributing Guidelines 💪🏻 and consider giving a star ⭐️ to our repository.

Our review team will carefully assess your merge and reach out to you soon!
We appreciate your patience!
