### ISSUE TITLE
Add Footer Section for Improved User Experience 

### ISSUE THREAD

**Issue by Sa2003hil** [Open-Source-Chandigarh/Streamix-IMDb#9]
Sample :
![image](https://github.com/Open-Source-Chandigarh/Streamix-IMDb/assets/115913715/df092f82-e161-43d3-97a9-e17e1c0e96ad)

**Comment by BhukyaShivaNayak** [comment]
Please assign this issue

**Comment by Sa2003hil** [comment]
Hey @BhukyaShivaNayak 
Congratulations we are assigning this issue to you ! 🎉 Your forthcoming contribution holds great value for us 😊
Make sure you'll make the footer component as given in the sample image and submit a pull request with a clear explanation of the changes you've made. Kindly ensure that you adhere to our Contributing Guidelines 💪🏻 and consider giving a star ⭐️ to our repository.

Our review team will carefully assess your merge and reach out to you soon!
We appreciate your patience!
